import { SurveyForm } from "./types"

export const formTemplates: SurveyForm[] = [
  {
    id: "template-1",
    title: "تقييم الدورة التدريبية",
    description: "استبيان لتقييم جودة الدورة التدريبية ومدى استفادة المتدربين",
    category: "تعليم",
    responses: 0,
    createdAt: new Date().toISOString(),
    isTemplate: true,
    questions: [
      {
        id: "q1",
        type: "rating",
        text: "كيف تقيم جودة المحتوى التعليمي؟",
        required: true,
      },
      {
        id: "q2",
        type: "rating",
        text: "كيف تقيم أداء المدرب؟",
        required: true,
      },
      {
        id: "q3",
        type: "radio",
        text: "هل كانت مدة الدورة مناسبة؟",
        options: ["قصيرة جداً", "مناسبة", "طويلة جداً"],
        required: true,
      },
      {
        id: "q4",
        type: "checkbox",
        text: "ما الجوانب التي أعجبتك في الدورة؟",
        options: ["المحتوى النظري", "التطبيقات العملية", "النقاشات الجماعية", "المواد المرفقة"],
        required: false,
      },
      {
        id: "q5",
        type: "textarea",
        text: "هل لديك أي اقتراحات لتحسين الدورة؟",
        required: false,
      },
    ],
  },
  {
    id: "template-2",
    title: "استبيان رضا العملاء",
    description: "قياس مستوى رضا العملاء عن الخدمات المقدمة",
    category: "خدمات",
    responses: 0,
    createdAt: new Date().toISOString(),
    isTemplate: true,
    questions: [
      {
        id: "q1",
        type: "rating",
        text: "ما مدى رضاك عن جودة الخدمة؟",
        required: true,
      },
      {
        id: "q2",
        type: "rating",
        text: "ما مدى سرعة الاستجابة لطلباتك؟",
        required: true,
      },
      {
        id: "q3",
        type: "radio",
        text: "هل ستوصي بخدماتنا للآخرين؟",
        options: ["بالتأكيد نعم", "على الأرجح نعم", "غير متأكد", "على الأرجح لا", "بالتأكيد لا"],
        required: true,
      },
      {
        id: "q4",
        type: "textarea",
        text: "ما الذي يمكننا تحسينه لخدمتك بشكل أفضل؟",
        required: false,
      },
    ],
  },
  {
    id: "template-3",
    title: "استطلاع رأي الموظفين",
    description: "استبيان لقياس رضا الموظفين وبيئة العمل",
    category: "موارد بشرية",
    responses: 0,
    createdAt: new Date().toISOString(),
    isTemplate: true,
    questions: [
      {
        id: "q1",
        type: "rating",
        text: "ما مدى رضاك عن بيئة العمل الحالية؟",
        required: true,
      },
      {
        id: "q2",
        type: "radio",
        text: "هل تشعر بالتقدير في عملك؟",
        options: ["دائماً", "غالباً", "أحياناً", "نادراً", "أبداً"],
        required: true,
      },
      {
        id: "q3",
        type: "checkbox",
        text: "ما الجوانب التي تحتاج لتحسين؟",
        options: ["التواصل", "فرص التطور", "التوازن بين العمل والحياة", "المكافآت والحوافز"],
        required: false,
      },
      {
        id: "q4",
        type: "textarea",
        text: "اقتراحاتك لتحسين بيئة العمل",
        required: false,
      },
    ],
  },
  {
    id: "template-4",
    title: "تقييم ورشة عمل",
    description: "استبيان لتقييم ورشة العمل والمهارات المكتسبة",
    category: "تعليم",
    responses: 0,
    createdAt: new Date().toISOString(),
    isTemplate: true,
    questions: [
      {
        id: "q1",
        type: "rating",
        text: "ما تقييمك العام لورشة العمل؟",
        required: true,
      },
      {
        id: "q2",
        type: "radio",
        text: "هل تحققت أهدافك من حضور الورشة؟",
        options: ["نعم بالكامل", "نعم جزئياً", "لا"],
        required: true,
      },
      {
        id: "q3",
        type: "checkbox",
        text: "ما المهارات التي اكتسبتها؟",
        options: ["مهارات تقنية", "مهارات تواصل", "مهارات قيادية", "مهارات تحليلية"],
        required: false,
      },
      {
        id: "q4",
        type: "textarea",
        text: "تعليقاتك الإضافية",
        required: false,
      },
    ],
  },
  {
    id: "template-5",
    title: "استبيان فعالية",
    description: "تقييم فعالية أو مؤتمر",
    category: "فعاليات",
    responses: 0,
    createdAt: new Date().toISOString(),
    isTemplate: true,
    questions: [
      {
        id: "q1",
        type: "rating",
        text: "كيف تقيم تنظيم الفعالية؟",
        required: true,
      },
      {
        id: "q2",
        type: "rating",
        text: "كيف تقيم المحتوى المقدم؟",
        required: true,
      },
      {
        id: "q3",
        type: "radio",
        text: "هل ستحضر فعالياتنا القادمة؟",
        options: ["بالتأكيد", "على الأرجح", "غير متأكد", "على الأرجح لا"],
        required: true,
      },
      {
        id: "q4",
        type: "textarea",
        text: "ما الموضوعات التي تود رؤيتها في الفعاليات القادمة؟",
        required: false,
      },
    ],
  },
  {
    id: "template-6",
    title: "استبيان منتج جديد",
    description: "جمع آراء العملاء حول منتج جديد",
    category: "تسويق",
    responses: 0,
    createdAt: new Date().toISOString(),
    isTemplate: true,
    questions: [
      {
        id: "q1",
        type: "radio",
        text: "كيف سمعت عن منتجنا الجديد؟",
        options: ["وسائل التواصل الاجتماعي", "الإعلانات", "توصية صديق", "البريد الإلكتروني", "أخرى"],
        required: true,
      },
      {
        id: "q2",
        type: "rating",
        text: "ما مدى اهتمامك بالمنتج؟",
        required: true,
      },
      {
        id: "q3",
        type: "checkbox",
        text: "ما الميزات الأكثر جاذبية لك؟",
        options: ["السعر", "الجودة", "سهولة الاستخدام", "التصميم", "الميزات الإضافية"],
        required: false,
      },
      {
        id: "q4",
        type: "textarea",
        text: "ما الميزات الإضافية التي تود رؤيتها؟",
        required: false,
      },
    ],
  },
]

export function generateId(): string {
  return Math.random().toString(36).substring(2, 15)
}
